---
language: ruby
cache: bundler
script:
    - "bundle exec rake validate lint spec SPEC_OPTS='--format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.6
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 4.5" STRICT_VARIABLES="yes"
  - rvm: 2.1.6
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 3.5" FUTURE_PARSER="yes"
  - rvm: 2.1.6
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 3.8"
  - rvm: 1.9.3
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 3.8"
notifications:
  email: false
